// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKxdMFLenBlXzkajIVf77ldSqp3OtMGkw',
    appId: '1:760131458678:web:da6500af5acf4797113157',
    messagingSenderId: '760131458678',
    projectId: 'moje-akwarium-40a75',
    authDomain: 'moje-akwarium-40a75.firebaseapp.com',
    storageBucket: 'moje-akwarium-40a75.firebasestorage.app',
    measurementId: 'G-YNF2L6Q5P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6RN0XYuIMi5eEOIGjkMCbAdFqxaxOqqE',
    appId: '1:760131458678:android:f8e04c550b9f6ddf113157',
    messagingSenderId: '760131458678',
    projectId: 'moje-akwarium-40a75',
    storageBucket: 'moje-akwarium-40a75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgUSopUL3fczymCg6QdMQzLAmMTeIWFAs',
    appId: '1:760131458678:ios:5a027a51df17df5c113157',
    messagingSenderId: '760131458678',
    projectId: 'moje-akwarium-40a75',
    storageBucket: 'moje-akwarium-40a75.firebasestorage.app',
    iosBundleId: 'com.example.akwarium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgUSopUL3fczymCg6QdMQzLAmMTeIWFAs',
    appId: '1:760131458678:ios:5a027a51df17df5c113157',
    messagingSenderId: '760131458678',
    projectId: 'moje-akwarium-40a75',
    storageBucket: 'moje-akwarium-40a75.firebasestorage.app',
    iosBundleId: 'com.example.akwarium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKxdMFLenBlXzkajIVf77ldSqp3OtMGkw',
    appId: '1:760131458678:web:9fb284a2bf008fb0113157',
    messagingSenderId: '760131458678',
    projectId: 'moje-akwarium-40a75',
    authDomain: 'moje-akwarium-40a75.firebaseapp.com',
    storageBucket: 'moje-akwarium-40a75.firebasestorage.app',
    measurementId: 'G-E3T2GCQRLL',
  );
}
